name: 'Deploy to premiere'

on:
  push: 
    branches: [main]

env:
  BETTER_AUTH_SECRET: ${{ SECRETS.BETTER_AUTH_SECRET }}
  BETTER_AUTH_URL: https://velvet-cup.munthe.dev/
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  MIDTRANS_CLIENT_KEY: ${{ vars.MIDTRANS_CLIENT_KEY }}
  MIDTRANS_SERVER_KEY: ${{ vars.MIDTRANS_SERVER_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          args: --prod
          cache: pnpm

      - name: 'Create env file'
        run: |
          echo "BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET" >> .env
          echo "BETTER_AUTH_URL=$BETTER_AUTH_URL" >> .env

          echo "MIDTRANS_CLIENT_KEY= $MIDTRANS_CLIENT_KEY" >> .env
          echo "MIDTRANS_SERVER_KEY= $MIDTRANS_SERVER_KEY" >> .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env

      - name: 'Build app with relevant env variables'
        run: 'export $(cat .env) && pnpm build'

      - name: 'Copy app to EC2 Premiere'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --include=".env" --include="node_modules/***" --include="dist/***" --include="package.json" --include="pnpm-lock.yaml" --exclude="*/"
          path: .
          remote_path: /var/www/velvet-cup.munthe.dev/
          remote_host: ${{ SECRETS.EC2_HOST }}
          remote_user: ${{ SECRETS.EC2_USER }}
          remote_key: ${{ SECRETS.EC2_PRIVATE_KEY }}

      - name: 'Configure SSH to restart app'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ SECRETS.EC2_USER }}
          SSH_KEY: ${{ SECRETS.EC2_PRIVATE_KEY }}
          SSH_HOST: ${{ SECRETS.EC2_HOST }}

      - name: 'Restart app'
        run: |
          ssh prod 'pm2 restart "velvet cup"'

